### ISSUE TITLE
linux ergo setup problem

### ISSUE THREAD

**Issue by sealse** [cristianoliveira/ergo#101]
Need can to set param's as port for Ubuntu 16.04

If:

ergo setup linux-gnome -p "2001"
Current detected system: linux
Setup failed cause exit status 2

Else:

ergo setup linux -p "2001"
Current detected system: linux

List of supported systems:

-linux-gnome
-osx
-windows

For more support please open an issue on: https://github.com/cristianoliveira/ergo

**Comment by cristianoliveira** [comment]
Hello @sealse Thanks for the report.

I think it is a bug related to the args. Shouldn't be that hard to fix it
Also, It isn't a use case we didn't thought about :)

**Comment by cristianoliveira** [comment]
Hey @sealse I just noticed you were passing an invalid `linux` to it. You suppose to pass `linux-gnome` 😄 
I just tried here and it is working just fine :)

**Comment by uocxp** [comment]
i have the same problem when i type `ergo setup linux-gnome` i get:
         
    Current detected system: linux
    Setup failed cause exit status 2
