### ISSUE TITLE
Feature: Add configurable Timeout

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#103]
As a user I'd like to have an option to configure a timeout for the proxy

**Comment by adiclepcea** [comment]
Is this a timeout like stop the proxy after the timeout has passed? Or perhaps, if the target page does not respond in the given timeout, stop trying to reach it?

**Comment by cristianoliveira** [comment]
Not really, it more if the service ergo is trying to reach is not available then It just cuts the connection after a given time. Sometimes it gets stuck on those connections. So giving the option to set a time out can free the proxy without manual intervention :)
