### ISSUE TITLE
BUG: proxy not working on ubunt 18.04

### ISSUE THREAD

**Issue by uocxp** [cristianoliveira/ergo#105]
i installed the program like mentioned in the README and tried `ergo setup linux-gnome` but i am getting
     
     Current detected system: linux
     Setup failed cause exit status 2

i tried then to do the configuration manually and added `http://127.0.0.1:2000/proxy.pac` to `System Settings > Network > Network Proxy > Automatic` but when i add a service `echo "example http://localhost:8080" > .ergo` and do `ergo run` i can't reach it through http://example.dev though i can reach localhost:8080

ergo version: v0.2.2

**Comment by cristianoliveira** [comment]
Hey @uocxp thanks for reporting it. I'll take a look on it this weekend :)

**Comment by xReprisal** [comment]
The problem seems to be with the way arguments are split in `Runner.Run()`. If instead of using runner inside `LinuxConfiguration.SetUp()` you run ```exec.Command(`/bin/sh`, `-c`, `gsettings set org.gnome.system.proxy mode 'auto' &&
      gsettings set org.gnome.system.proxy autoconfig-url 'http://127.0.0.1:2000/proxy.pac'`).Run()``` there is no error returned. Same goes for  `LinuxConfiguration.SetDown()`

**Comment by cristianoliveira** [comment]
Hey @xReprisal Thanks for this debugging  :)

I'll provide a fix as soon as possible.

**Comment by cristianoliveira** [comment]
Sorry guys for the late response to this issue. I'm currently moving into a new apartment and it is consuming all my spare time lately :(

I hope I can go back to normal soon and then debug those things :)

**Comment by EdByrnee** [comment]
+1

**Comment by cristianoliveira** [comment]
I'll close this issue. Feel free to open again if it is still happening.
