### ISSUE TITLE
On Linux Kubuntu 16.04 I get DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by anodynos** [cristianoliveira/ergo#106]
Everything seems to be installed properly, but it gives me a `DNS_PROBE_FINISHED_NXDOMAIN` when I try to connect to my alias. 

My setup is: 

```
╰─$ echo $http_proxy                                                                     
http://localhost:2000
╰─$ ergo list
Ergo Proxy current list:
 - http://portainer.dev -> http://127.0.0.1:9000
```
Proxy config is: 
![image](https://user-images.githubusercontent.com/856453/46905561-8a708100-ceed-11e8-8e46-d1f25ddad067.png)
and I can download `http://127.0.0.1:2000/proxy.pac` as

```
		function FindProxyForURL (url, host) {
			if (dnsDomainIs(host, '.dev')) {
				return 'PROXY 127.0.0.1:2000';
			}

			return 'DIRECT';
		}
```

I then run Chrome alone or `╰─$ google-chrome --proxy-pac-url=http://localhost:2000/proxy.pac`

and all I get is:

```
This site can’t be reached
portainer.dev’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

Any ideas?

**Comment by cristianoliveira** [comment]
I ask you to try out it with that config because sometimes if you lunch ergo while your browser is still opened it doesn't use the auto config proxy settings. Perhaps an internal browser DNS cache.

**Comment by yuriw** [comment]
I guess I am seeing the same issue too and ref: #107

**Comment by cristianoliveira** [comment]
As I mentioned at #107. I just tested on my Ubuntu 17.04 and it's working fine. I've used the settings that are inside the `examples` folder. I'm about to release a new version that fixes the `setup` command. Could you please try again then?

**Comment by yuriw** [comment]
@cristianoliveira sure  I will
