### ISSUE TITLE
Issues on ubuntu 16.04

### ISSUE THREAD

**Issue by yuriw** [cristianoliveira/ergo#107]
Installed 
as `curl -s https://raw.githubusercontent.com/cristianoliveira/ergo/master/install.sh | sh`

configure did not work

`ergo setup linux-gnome
Current detected system: linux
Setup failed cause exit status 2`

Also set Network Proxy to Automatic in Settings.

Added service as `echo "sabnzb https://localhost:9090" > .ergo`

ergo list
Ergo Proxy current list:
http://sabnzb.dev -> https://localhost:9090
(how do I change `http` to `https` ^ ?)

Of cause, this does not work :(

What am I doing wrong ?

**Comment by cristianoliveira** [comment]
Are you using `https` locally? Unfortunately, ergo is not able to intercept those requests yet. Did you try using `http`?

**Comment by yuriw** [comment]
@cristianoliveira I tried 
Ergo Proxy current list:
 - http://sonarr.dev -> http://localhost:8989 
and got `DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by cristianoliveira** [comment]
I'll have to test it at home where I have a Lubuntu running.

**Comment by yuriw** [comment]
@cristianoliveira any updates ?  I like the idea but so far don't see it's working on ubuntu 16.04 :(

**Comment by cristianoliveira** [comment]
Sorry @yuriw for the late response to this issue. I'm currently moving in to a new apartment and it is consuming all my spare time lately :(

I hope I can go back to normal soon and then debug those things :)

**Comment by yuriw** [comment]
@cristianoliveira sure, standing by

**Comment by cristianoliveira** [comment]
Hey @yuriw just tested here using the `/examples` folder on my Ubuntu 17 and it is working fine. I'm about to merging the #113 which will fix the `setup` command. Could you please try again with this new version?

**Comment by cristianoliveira** [comment]
The release https://github.com/cristianoliveira/ergo/releases/tag/v0.2.5 contains the setup command fix :)

**Comment by yuriw** [comment]
@cristianoliveira maybe I missing some step.  Here is what I did:

removed old version
`sudo rm /usr/local/bin/ergo` (BTW print message needs to be fixed it says now `rm /usr/local/binergo`) 
 
`curl -s https://raw.githubusercontent.com/cristianoliveira/ergo/master/install.sh | sh`

`ergo -v`
`v0.2.5`
`ergo list`
`Ergo Proxy current list:
 - http://sonarr.dev -> http://localhost:8989`

`ergo run
Ergo Proxy listening on port 2000 for domains .dev`

Open browser URL `http://sonarr.dev` ->   `This site canât be reached sonarr.devâs server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAINF`

**Comment by yuriw** [comment]
@cristianoliveira you mentioned "using the /examples folder on my Ubuntu 17", what are those ?

**Comment by cristianoliveira** [comment]
These examples:
https://github.com/cristianoliveira/ergo/tree/master/examples

Could you try not using `.dev` since it's considered a valid TLD and might be blocked it's usage by the browser. Try: `ergo run -domain .dav` for instance

**Comment by yuriw** [comment]
@cristianoliveira 
I messed up something, pls advise:

`ergo "http://sonarr.dov -> http://localhost:8989" > .ergo`

`ergo list-names`
2018/10/31 12:29:07 Could not load services: file error: invalid format `The management apps running on different ports made easy through custom local domains.` expected `{NAME} {URL}`

**Comment by cristianoliveira** [comment]
Could you run ergo with verbose flag `-V` and see if it gets at least some output?

**Comment by yuriw** [comment]
@cristianoliveira  running "ergo run -V
Ergo Proxy listening on port 2000 for domains .dev"
and hitting  `sonarr.dev` shows nothing.

What is interesting that when I open "http://sonarr.dev" my browser ends up with "https://sonarr.dev" 
DNS_PROBE_STARTED and then  DNS_PROBE_FINISHED_NXDOMAIN messages

**Comment by yuriw** [comment]
@cristianoliveira It'd be useful if you list exactly what you do for example when you add `sonarr` on `localhost:8096`, ALL commands please

**Comment by yuriw** [comment]
@cristianoliveira I am still hopeful, but so far no updates from you :(

**Comment by cristianoliveira** [comment]
I sincerely don't know how to help you. I've been using it with no problem so far.

If you tried to set it up as your direct proxy and didn't work so I need more info to help. :(

**Comment by yuriw** [comment]
@cristianoliveira Can you provide ALL steps you used on ubuntu pls ?

**Comment by galloaleonardo** [comment]
Hello!

A have same problem here =(

![image](https://user-images.githubusercontent.com/35380659/111480703-07ccfb00-8711-11eb-88ec-7efa5b258117.png)

![image](https://user-images.githubusercontent.com/35380659/111480918-39de5d00-8711-11eb-8196-163e1a0bb787.png)

![image](https://user-images.githubusercontent.com/35380659/111480961-42cf2e80-8711-11eb-85e9-abb8d20e05d2.png)

![image](https://user-images.githubusercontent.com/35380659/111481146-70b47300-8711-11eb-9bb1-549692c36539.png)


Ubuntu 20.04.2 LTS

**Comment by cristianoliveira** [comment]
Hey @galloaleonardo

When using a proxy on a terminal there is a special variable `export http_proxy="http://localhost:2000"` to tunnel the request through it. Here the an it is how to do it  https://github.com/cristianoliveira/ergo#using-on-terminal

Try this
```
export http_proxy="http://localhost:2000" curl http://ergoproxy.dev
```
