### ISSUE TITLE
Default domain (.dev) redirects to https on Chrome and Firefox

### ISSUE THREAD

**Issue by PieterScheffers** [cristianoliveira/ergo#108]
On Chrome and Firefox the hsts has been build in for the .dev domain. This means the browser automatically redirects to https.

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by EdByrnee** [comment]
There is an option to intercept custom domains but I can't find it in the documentation

**Comment by cristianoliveira** [comment]
Hey @PieterScheffers thanks for the report back. Yeah, `.dev` has been considered a real domain for a while now that's why we have this issue https://github.com/cristianoliveira/ergo/issues/58

It was partially solved by `-domain` flag or `ERGO_DOMAIN` env.  Are those options not working for you?

**Comment by cristianoliveira** [comment]
I'll close this. Please feel free to open again if the problem persist
