### ISSUE TITLE
Feature: subdomains?

### ISSUE THREAD

**Issue by metaperture** [cristianoliveira/ergo#11]
Hey, I just came across this via an answer on stackoverflow. I'd love to be able to use this, but I have a few local servers across subdomains, and I do need them to be subdomains, I can't just use different domains for them because they share cookies.

Thanks for the project, and I'm a big Ergo Proxy fan too :)

**Comment by metaperture** [comment]
This might work by changing https://github.com/cristianoliveira/ergo/blob/master/proxy/config.go#L30
to
```go
name := host[:len(host)-len(c.Domain)-1]
```
I'm going to go check that....

**Comment by cristianoliveira** [comment]
Hallo @metaperture! Thanks for the report. Exactly that is definitely the logic that we should change that will enable us using subdomains like `http://one.foo.dev` and `http://two.foo.dev`.

I will take a look later. :)

**Comment by cristianoliveira** [comment]
Hey @metaperture just pushed the changes that enable create local domains like: `one.domain`, `two.domain` and also `one.two.domain`. Let me know if it is what you need

**Comment by metaperture** [comment]
Just tested it--it works perfectly thanks! This is definitely going to be a useful part of my dev toolchain :)

**Comment by cristianoliveira** [comment]
Thank you! This tool has been helping me too :)

[v0.1.5](https://github.com/cristianoliveira/ergo/releases/tag/v0.1.5) include this feature

**Comment by maturano** [comment]
🤔 ... This also requires to be a `.dev` domain, right?.

I have the same issue with shared cookies. There is a domain that set the cookie for `.domain.com`; I don't have control over this. So I want run onto a `local.domain.com` in order catch be able to read the cookie. Is that possible?

**Comment by cristianoliveira** [comment]
Technally if you set run ergo using  a `.com` domain it supposed to work. Only for `http` websites for now though :/
