### ISSUE TITLE
PowerShell | "The system cannot find the file specified."

### ISSUE THREAD

**Issue by SkyEngine-OSP** [cristianoliveira/ergo#114]
after installing ergo via powershell using the `Invoke-WebRequest` command, i'm receiving this issues when running the `ergo setup windows` command:

`PS C:\xampp\htdocs\> ergo setup windows`
`2019/03/22 00:16:23 Could not load services: file error: open ./.ergo: The system cannot find the file specified.`

anybody receiving the same issue, or does anybody know what i've done wrong?

**Comment by cristianoliveira** [comment]
This is definitely a bug. Although if you want to avoid this error now you can provide an `.ergo` file before setting up the system. Something like:
```bash
echo "localhost:3000" > .ergo && ergo setup windows
```

I'll provide a fix
