### ISSUE TITLE
Ergo setup fails on Windows

### ISSUE THREAD

**Issue by consultwithmike** [cristianoliveira/ergo#115]
I installed Ergo via PowerShell per the documentation:

```
Invoke-WebRequest https://raw.githubusercontent.com/cristianoliveira/ergo/master/install.ps1 -out ./install.ps1; ./install.ps1
```

and that seemed to work.  I then added some configuration:

```
ergo add nbsalesapigateway-local http://localhost:27362
```

Executing `ergo list` provides me with the list I'd expect:

```PS C:\Users\Michael Perrenoud\Ergo> ergo list
Ergo Proxy current list:
 - http://nbsalesapigateway-local.dev -> http://localhost:27362
```

However, `ergo setup windows` fails:

```
PS C:\Users\Michael Perrenoud\Ergo> ergo setup windows
Current detected system: windows
Setup failed cause exit status 1
```

and I've noticed that `ergo run` fails with an interesting error (maybe related to the fact that `setup` has never succeeded):

```
PS C:\Users\Michael Perrenoud\Ergo> ergo run
Ergo Proxy listening on port 2000 for domains .dev
listen tcp :2000: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

**Comment by souljedi** [comment]
Similar issue here: `ergo setup windows` fails with the same message. However, when running `ergo run` i don't get the same warning as @consultwithmike. For me it only says `Ergo Proxy listening on port 2000 for domains .dev`.

I also tried to configure manually in the system's network settings, followed by a system restart without success. It's listening on port 2000 (firewall exception added), but redirect in browser fails.

I'm on Windows 10 Version 1903 OS Build 18362.175, using Firefox version 67.0.4 64bit.

**Comment by cristianoliveira** [comment]
Hello there.

I think is because you need to run set up as admin user I'd guess. I'm not familiar with Windows permission system but It's strange it requiring permission to run a simple server. Can you double-check if it has the correct permissions to do so?

**Comment by cristianoliveira** [comment]
About your question @souljedi, could you test using a different CTL besides `.dev` using the `-domain` parameter?

**Comment by cristianoliveira** [comment]
Since there is no answer to this question I'll assume you figure it out :)

**Comment by cahyowhy** [comment]
i also got this issue

**Comment by namcodes** [comment]
same problem, please help me some steps
