### ISSUE TITLE
firefox support?

### ISSUE THREAD

**Issue by CastixGitHub** [cristianoliveira/ergo#117]
Hello,
From my terminal after `http_proxy` is set if I do a curl request I get it on the ergo run log and I get the right response. 
I've set `Automatic proxy configuration URL` in firefox, when I open .dev domain what happens is weird: the scheme is changed to https and no log is provided, I get a 404 response.

**Comment by CedricFinance** [comment]
Hi,
I think it's linked to HSTS on .dev domains.
I checked on Chrome: `chrome://net-internals/#hsts`
![image](https://user-images.githubusercontent.com/3935032/73690987-c5de2280-46d1-11ea-9bce-8f2b63330951.png)

**Comment by muisje** [comment]
Does not work for me either. Am using firefox/
This is what happens when i visit jellyfin.dev

> Hmm. We’re having trouble finding that site.

We can’t connect to the server at jellyfin.dev.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.

Erglo list output:

```
ergo list
Ergo Proxy current list:
 - http://jellyfin.dev -> http://pi:8096

```

when i visit the site with curl the ergo run outputs a new line, but with firefox it does not.

ergo run
```
Ergo Proxy listening on port 2000 for domains .dev
[2020-05-03 16:58:50] GET http://jellyfin.dev/ HTTP/1.1
```

When i visit it in firefox with ergo not running: 

> The proxy server is refusing connections

Firefox is configured to use a proxy server that is refusing connections.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to make sure the proxy server is working.

**Comment by cristianoliveira** [comment]
Hey guys.

Sorry for the absence, personal issues.

Did you manage to make it run?
This issue with `.dev` isn't it related to this one https://github.com/cristianoliveira/ergo/issues/58 ?

Regards,

PS. if there is no answer to this in a week I'll assume you figure it out and I will close this issue 😊

**Comment by CastixGitHub** [comment]
Actually I did't use ergo because of this issue, just looked into this again.
firefox works by checking `Proxy DNS hen using SOCKS v5` option (and proxy pac as usual)
as stated in other issues, does not work (redirects to https) for `.dev` domains so I used `ergo run -domain .test`

~~fun fact: I'm not able to make it work with chromium (`chromium --proxy-pac-url=http://localhost:2000/proxy.pac`) dns query fails~~ (cache cleared, now working too)

**Comment by cristianoliveira** [comment]
Which version of firefox are you using? So I can try to debug myself later.
