### ISSUE TITLE
Feature: auto config system proxy settings

### ISSUE THREAD

**Issue by metaperture** [cristianoliveira/ergo#12]
I quickly set up the following wrapper--maybe something like it should be baked in, and triggered on a flag? This one is Ubuntu-only:

```bash
function finish {
  # these should probably revert to original settings
  gsettings set org.gnome.system.proxy mode "none"
  gsettings set org.gnome.system.proxy.http host ""
  gsettings set org.gnome.system.proxy.http port "8080"
}
trap finish EXIT

gsettings set org.gnome.system.proxy mode 'auto'
gsettings set org.gnome.system.proxy autoconfig-url http://127.0.0.1:2000/proxy.pac 

$GOPATH/bin/ergo run
```

**Comment by cristianoliveira** [comment]
Hey @metaperture that is awesome! Maybe creating a script for each distribution as an alternative way to setup it. I will take a look to see if I can find something like for `osx` too

**Comment by cristianoliveira** [comment]
Hey @metaperture 
I just create a PR https://github.com/cristianoliveira/ergo/pull/14 that adds the `setup` command, which was based on your suggestion :)
Also added scripts for ephemeral proxy setup inside of `/resources` folder as an alternative.
