### ISSUE TITLE
validation of configured addresses

### ISSUE THREAD

**Issue by CastixGitHub** [cristianoliveira/ergo#120]
shoud block the user immediatly whit urls like

```
http:/localhost:8080
http:loalhost:8080
http://localhost:
http://localhost:asd

http://localhost:8080/no   <- actually works but adds a leading `/` (needs a separate issue?)
localhost:8080 <- should be guessed it's http?
```

this should happen when services are added, and at ergo startup

**Comment by cristianoliveira** [comment]
Hey @CastixGitHub thanks for reporting this. 
Yeah, I agree, this should be validated! It shouldn't be hard to implement such validations.
