### ISSUE TITLE
Feature: Wildcard subdomains?

### ISSUE THREAD

**Issue by clytras** [cristianoliveira/ergo#122]
I can see there is a feature supporting subdomains with https://github.com/cristianoliveira/ergo/issues/11 and I'd like to ask if it would be possible to add wildcard subdomain support, something like the following format:

```
*.mydomain http://localhost:8080
```

will resolve to every subdomain automatically, like:

```
test.mydomain.dev
user10.mydomain.dev
admin.mydomain.dev
```

There are applications that have such features to generate subdomains and of course this is configurable in a DNS level and there are even wildcard SSL certificates and having such a feature for developement environment using Ergo would be awesome!

**Comment by cristianoliveira** [comment]
I know it's been a while but this feature is now implemented on ergo and soon will be merged :D
