### ISSUE TITLE
Use across home network?

### ISSUE THREAD

**Issue by paxperscientiam** [cristianoliveira/ergo#130]
Hello!

I'm testing out `ergo` and it works amazingly well.

Out of curiosity, I tested if I could get `ergo` working across my local network (all mac machines). 

Machine A is running `ergo`. So, on Machine B, I set Automatic Proxy Configuration to http://<local_domain_for_machine_a>:2000/proxy.pac (I also tried the IP address for Machine A).

That said, once I viewed the contents of proxy.pac, I knew it wouldn't work as the code references the loopback address rather than the address of Machine A.

In this moment, can `ergo` be used to make services available across a home network via their Ergo proxy domain names?

**Comment by cristianoliveira** [comment]
Hey @paxperscientiam That wasn't the intended usage of ergo. I bet that with enough effort put into it you can make it work.  But I'd rather recommend looking for other alternatives like maybe rolling your own local DNS and redirecting the addresses you use externally to the internal IP addresses when accessed from within your LAN. You can use something like Dnsmasq.

**Comment by paxperscientiam** [comment]
Thanks for the suggestion about dnsmasq.
