### ISSUE TITLE
Wrong format in README

### ISSUE THREAD

**Issue by Jatoxo** [cristianoliveira/ergo#141]
According to the readme, the format is
url:port + space + domain

but it's actually
domain + space + url:port

even in the instructions below they are the wrong way around

**Comment by cristianoliveira** [comment]
Hey @Jatoxo thanks for reporting. After the merge of https://github.com/cristianoliveira/ergo/pull/137 it should work both ways. I'll release it on the new version

**Comment by cristianoliveira** [comment]
I'll add a warning in the docs

**Comment by Jatoxo** [comment]
I ran the install command for Linux. The .version file still says "v0.2.5", so I guess it installed an older version

**Comment by cristianoliveira** [comment]
No worries, your report made me realize, there might be still people using the old version, so it's better to keep the docs pointing to the format that work on both :D

**Comment by Jatoxo** [comment]
True

You should probably still bump the version in .version so the install script will grab the newest version for new installs 😅

**Comment by cristianoliveira** [comment]
Done!

Also, after merging this [PR](https://github.com/cristianoliveira/ergo/pull/143) you should be able to install any version listed in [Releases](https://github.com/cristianoliveira/ergo/releases) :)

**Comment by cristianoliveira** [comment]
Fixed by 642510a38e4bad37436ebf36b908b06b16d010c7 and 3ad76b366d327bb82328d64b4a83d39eb91dbbdf

**Comment by cristianoliveira** [comment]
Thanks again for reporting! Let me know if the fixes are working for you :)

**Comment by Jatoxo** [comment]
Yup, LGTM 👍
