### ISSUE TITLE
bug: windows  v0.3.1-2-g3b8840f build giving error when use setup command

### ISSUE THREAD

**Issue by thexmeta** [cristianoliveira/ergo#147]
I built myself in my machine ergo version of v0.3.1-2-g3b8840f. Also `make test` results are all "PASSED".
 I am getting below error somehow when using setup.

```
ergo setup windows
2024/01/09 09:20:48 -------------MISSING CONFIG FILE---------------
2024/01/09 09:20:48 Please make sure a file named `.ergo` is present in this path:
2024/01/09 09:20:48 Config file path: ./.ergo
2024/01/09 09:20:48 Error: invalid service format `"ergoproxy http://localhost:3000" ` expected `{NAME} {URL}`
Current detected system: windows
Setup failed cause exit status 1
```

**Comment by cristianoliveira** [comment]
Hello there @thecodymeta 

Thanks for reporting! I was on vacations last month. I'll take a look as soon as possible

**Comment by cristianoliveira** [comment]
@thexmeta I believe the error you were getting was related to the extra spaces left in the service line. I made a small fix for that I'll release. Let me know if the it solves the issue

**Comment by thexmeta** [comment]
now i am getting different error when using new executable version of 0.4.0
```
ergo run
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x77ae73]

goroutine 1 [running]:
net/url.(*URL).Hostname(...)
        C:/hostedtoolcache/windows/go/1.22.2/x64/src/net/url/url.go:1151
github.com/cristianoliveira/ergo/proxy.NewService({0xc000010660, 0xa}, {0xc00001066b, 0x16})
        D:/a/ergo/ergo/proxy/service.go:27 +0xd3
github.com/cristianoliveira/ergo/proxy.readServicesFromFile({0x80881a, 0x7})
        D:/a/ergo/ergo/proxy/config.go:231 +0x35a
github.com/cristianoliveira/ergo/proxy.(*Config).LoadServices(0xc00011e1c0)
        D:/a/ergo/ergo/proxy/config.go:151 +0x27
main.main()
        D:/a/ergo/ergo/main.go:172 +0x166
```

**Comment by cristianoliveira** [comment]
Hey @thexmeta thanks for reporting. Could you share your .ergo file that you are trying to use?

**Comment by cristianoliveira** [comment]
I'm reopening the issue, but I'm suspect is a different issue

**Comment by thexmeta** [comment]
Hey @cristianoliveira , this is my  .ergo file content, actually its default:

"ergoproxy http://localhost:3000"

**Comment by thexmeta** [comment]
btw error is same for 0.4 and 0.3 versions. I guess app is looking wrong directories for go and ergo.
C:/hostedtoolcache/windows/go
and 
D:/a/ergo

I dont have both of them in my computer.

Should I need to define any environment variables for making it work?
like  GOPATH and ERGO ?

**Comment by cristianoliveira** [comment]
Thanks again @thexmeta I believe I found the error and already opened a PR, I'll include a test before merging it and releasing a new version :D
