### ISSUE TITLE
Tests: Add some integration tests

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#16]
We need to add some integration tests cause part of the code remains untouched by the current tests like the `/commands`.

**Comment by adiclepcea** [comment]
@cristianoliveira  Please see https://github.com/cristianoliveira/ergo/pull/44.
All the commands are tested now. But there are some suggestions in the comments there.

**Comment by adiclepcea** [comment]
After #46 is closed, this should also be closed.

**Comment by cristianoliveira** [comment]
Your wish is my command sir :+1:

**Comment by adiclepcea** [comment]
😆
