### ISSUE TITLE
bug: Linux script to install latest version failing

### ISSUE THREAD

**Issue by jonas-scytech** [cristianoliveira/ergo#171]
Hey, first, ty for your work. 

I tried to install the latest version using this command from the README: `curl -s https://raw.githubusercontent.com/cristianoliveira/ergo/master/install.sh | sh`

but it fails with the message `install.sh: [FATAL] unable to download package`

It seems it's trying to download the version v0.4.2.

**Comment by cristianoliveira** [comment]
Hey @jonas-scytech 

Let me check! I'll to add a building check in CI for these linux install scripts

**Comment by cristianoliveira** [comment]
Indeed the version file was 0.4.2 but the latest tag is 0.4.1 
https://github.com/cristianoliveira/ergo/blob/b2b9e6b4eff543774bfed5724833950176c911a0/.version#L1

Fixed and added a check in the integration job

**Comment by cristianoliveira** [comment]
Done! 
Now there is a check on every build and hopefully no more invalid scripts :) 
https://github.com/cristianoliveira/ergo/blob/master/.github/workflows/on-push-integration.yml#L25

**Comment by cristianoliveira** [comment]
Let me know if it's working, if not feel free to reopen the issue
