### ISSUE TITLE
docs: Create a Demo gif in good quality

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#21]
That is simple. Just record your screen basically doing the same steps that we have on currently demo. After you will need to parse this video into an Animated GIF. Please make sure that the quality is good enough. Then override the `demo.gif` with your new one.

Feel free to ask any questions regarding this process.

**Comment by TraGicCode** [comment]
I'll start working on this one

**Comment by TraGicCode** [comment]
Unforuntaly i couldn't get this to work on mac.  The webbrowser just hung locally.  Looks like a bug?

**Comment by kalbhor** [comment]
This seems open. Can I work on this?

**Comment by cristianoliveira** [comment]
Hey @TraGicCode what exactly didn't work? Have you used the `setup` command? Sometimes the browser takes some time to start using the configured proxy.

Hey @kalbhor it seems that @TraGicCode is working on it. I just opened a new one here take a look #24

Thank you for the help :D

**Comment by cristianoliveira** [comment]
Hey @TraGicCode are you still interested in working on it?
