### ISSUE TITLE
Chore: Ensure build before running tests

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#25]
When running the tests it tries to find an `ergo` binary inside of `bin` folder.
In order to ensure that it will be there, we should include it into Makefile:

```make
test: build
	@go test ./... -v
```

and then use `make test` for testing.

PLUS: Would be nice to have a section on `README` (Testing) about how to test properly the project. Something like this: 
https://github.com/cristianoliveira/funzzy#tests

refers to #24

**Comment by sitaramshelke** [comment]
Looking into this.
