### ISSUE TITLE
Tests: Skip integration tests without the presence of "-integration" flag

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#26]
We want to avoid run integration tests (tests inside `tests` folder) when not passed the flag `-integration` to go test command. `go test .../. -v -integration`.

Please take a look on how to implement this here:
https://siongui.github.io/2017/04/28/command-line-argument-in-golang-test/

This refers to #24

**Comment by mileswilson** [comment]
Would you be open to implementing this as an environment variable?

Using flags means you have to implement the flag in all packages if you run tests using 

`go test .../.`

else you get ```
flag provided but not defined: -integration```
messages in your tests for packages that do not define it.

I've pushed a commit that provides this functionality  through an environment variable called INTEGRATION_TEST

Let me know if you'd like me to raise a PR.

**Comment by cristianoliveira** [comment]
Hey @mileswilson sure it is. The point here is just avoiding run integration tests when it isn't required.

**Comment by cristianoliveira** [comment]
Regarding your commit, I think it is exactly what we need. Feel free to open a PR :)

**Comment by zmb3** [comment]
Hey @mileswilson  - it is possible to use a flag here - there was a [great talk](https://about.sourcegraph.com/go/advanced-testing-in-go/#golden-files-also-test-flags) at GopherCon regarding the topic.

You can define flags in your _test.go files and they only take effect when testing.  So a simple line like:

```
var integration = flag.Bool("integration", false, "run integration tests")
```

and a gate

```
func TestIntegration(t *testing.T) {
	if !*integration {
		t.Skip("skipping integration tests, run with -integration")
	}
	// ...
```

should be all that's needed for `go test ./... -integration` to work.
