### ISSUE TITLE
bug: Error when ergo file has a bad format.

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#32]
While testing on windows I noticed that when running ergo using a bad file it raises the follow error:
```
ergo run
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/cristianoliveira/ergo/proxy.LoadServices(0x12d8403, 0x7, 0x0, 0x0, 0x0)
        /Users/cristianoliveira/go/src/github.com/cristianoliveira/ergo/proxy/config.go:61 +0x43e
main.main()
        /Users/cristianoliveira/other/ergo/main.go:58 +0x2f2
```

The file `.ergo` content:
```
foo
```

**Comment by cristianoliveira** [comment]
The problem is right here:
https://github.com/cristianoliveira/ergo/blob/master/proxy/config.go#L74

When the file isn't correct the array doesn't have the right number of indexes

**Comment by eugecm** [comment]
Should it print an error saying that the file has an invalid format for example?

**Comment by cristianoliveira** [comment]
hey @eugecm yeah! 
Anything is better than blowing up the stack trace in our face 😅

**Comment by eugecm** [comment]
Alright @cristianoliveira, I can work on this.
