### ISSUE TITLE
Separate unit and integration tests

### ISSUE THREAD

**Issue by adiclepcea** [cristianoliveira/ergo#34]
This is just a suggestion.
I was thinking that maybe it is better to separate the unit tests from the integration tests (which seem to be more end-to-end tests - see what [a Google blog](https://testing.googleblog.com/2010/12/test-sizes.html) says). This is in the **Makefile** of course.
This way we can test the code with the unit tests without compiling the binary and then run the integration/end-to-end tests only after the build. 
I say that these could be end-to-end tests especially when we add the tests for the **setup** and for the **run** . As the **setup** and **run** part especially should test if the proxy is being used, and also if an outside page will be accessible while running the proxy.
The new flow would be:
1. Run the unit tests
2. Run the build
3. Run the end-to-end tests
4. Create the releases (if it is the case).
This would solve the problem with the tests depending on the executable.

**Comment by cristianoliveira** [comment]
Hey @adiclepcea totally agree with this. In order to achieve it isn't just changing the `test` task inside Makefile to not build before?

**Comment by adiclepcea** [comment]
Yes. That was what I was thinking. 
To use the **test** target that we have now for unit testing and to create a new target in the make file named **test-integration** (maybe) that will run the integration test.
The **test-integration** target should depend on the **build** target.
The **test** target should not.

**Comment by cristianoliveira** [comment]
Looks good to me. Do you want to make those changes?

**Comment by adiclepcea** [comment]
Yep. I'm on it

**Comment by Nightpanda** [comment]
Hi. How come this issue is still open? All evidence points to this issue being solved.

**Comment by adiclepcea** [comment]
Yep. It is done by #40. I will close it.
