### ISSUE TITLE
docs: Fix typos and improve description - Hacktoberfest

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#37]
Hello, fellow Hacktoberfest contributor!

I am opening this issue especially for Hacktoberfest. I am not a native English speaker and I am so used to read the project readme that I am not able to see all typos it might have.

So I invite you to take a look at it and if you find out either a typo or a weird sentence please feel free to point it out and open a PR with a fix for it. 😄

Also feel free to suggest description changes to make it easier to understand the purpose of this project/app 😃 

**Please make sure you point this issue on your PR (refers #37)**

**⚠️UPDATE: We are having a lot of PR for this. Please make sure you took a look at others Open PRs before opening a new one :)**

Please feel free to ask anything.

**Comment by abdulamite** [comment]
I'll take it!
