### ISSUE TITLE
Tests for OSX just skip if the setup does not complete

### ISSUE THREAD

**Issue by adiclepcea** [cristianoliveira/ergo#46]
In #44 the tests for OSX just skip if the setup fails. 
This happens here:
https://github.com/cristianoliveira/ergo/blob/master/tests/ergo_run_test.go#L362
and here:
https://github.com/cristianoliveira/ergo/blob/master/tests/ergo_run_test.go#L508

There is also a mention in the comments there.
They should fail if setup fails just like Linux and Windows tests do.

**Comment by adiclepcea** [comment]
@cristianoliveira 
I had access to a desktop mac today. It seems that the problems comes from the fact that the code is dependent on the ```Wi-Fi``` network. If I replaced the ```Wi-Fi``` with ```Ethernet``` here, than it worked ok.
see https://github.com/cristianoliveira/ergo/blob/master/commands/setup.go#L52
and
https://github.com/cristianoliveira/ergo/blob/master/commands/setup.go#L54
Another option would be to replace the line with something like:
```
sudo networksetup -setautoproxyurl "$(networksetup -listallnetworkservices | grep -v '*' | head 1)" "` + proxyURL + `"
```
This should take the first network found. 
For me it is hard to test it though.

**Comment by cristianoliveira** [comment]
Hey @adiclepcea 

I think that works. Another option is setting this for every network like is done in https://github.com/cristianoliveira/ergo/blob/master/resources/osx-setup-runner.sh

I will take a look on this later

**Comment by adiclepcea** [comment]
:+1:
