### ISSUE TITLE
Use a separate temporary config file for testing

### ISSUE THREAD

**Issue by adiclepcea** [cristianoliveira/ergo#52]
Right now there is a repetitive code that copies the original content of the config file at the beginning of the test and then rewrites it at exit so that we can have the same values at each test.
see 
* https://github.com/cristianoliveira/ergo/blob/master/tests/ergo_run_test.go#L113
* https://github.com/cristianoliveira/ergo/blob/master/tests/ergo_run_test.go#L599
* https://github.com/cristianoliveira/ergo/blob/master/tests/ergo_run_test.go#L672
* https://github.com/cristianoliveira/ergo/blob/master/tests/ergo_run_test.go#L672

A file copy of the original config should be done and that should be used instead. This could be put in a separate method to avoid code repetition.

**Comment by josledp** [comment]
I'll get this one

**Comment by adiclepcea** [comment]
:+1:

**Comment by adiclepcea** [comment]
Solved by @josledp
