### ISSUE TITLE
Install script should support multiple OS and Platform

### ISSUE THREAD

**Issue by ebastos** [cristianoliveira/ergo#54]
Considering Go is easily supported by multiple Operating Systems and platforms, the install script should be flexible enough to allow future expansion beyond Linux x64.

**Comment by adiclepcea** [comment]
In order to support FreeBSD I have modified ```.travis.yml``` and much of the files in the ```ci``` folder.
The modifications are in #51. Which fastly becomes too large :). I am no expert in travis, but I believe the builds are only done on releases. So I have no way of verifying the modifs now.

**Comment by cristianoliveira** [comment]
Closing this one because the project has changed direction
