### ISSUE TITLE
Bug: Error ERR_ICANN_NAME_COLLISION

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#58]
I am having the following error sporadically:
 
Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION

I searched around to understand it and reached this thread. 
https://superuser.com/questions/919278/err-icann-name-collision-when-trying-to-use-localhost-dev-in-chrome

It seems it occurs because `.dev` domain has become a registered ICANN Top Level Domain. So some domains that really exist and are registered can collide.

So I would like to open a discussion for changing the `.dev` to another TLD which is not registered yet. 

My suggestions would be `.local` but I am not convinced about this option yet

What do you think?

**Comment by adiclepcea** [comment]
Yes, ```dev``` is registered. I have noticed this also. I do not know about ```local```, but that  could easily be already registered. I have another proposition.
How about: ```.ergo```?

**Comment by cristianoliveira** [comment]
Yeah I thought about `.ergo` it's a nice option. I would like to have a second option also, something more "perennial" since no one knows if `.ergo` wouldn't one day become a TLD in the future? 😆 🤔 

After some research, I found those as already defined TLD that will never change, since it is on the DNS RFC specifications.

> To safely satisfy these needs, four domain names are reserved as
listed and described below.
  .test
  .example
  .invalid
  .localhost

> ".test" is recommended for use in testing of current or new DNS
related code.

>".example" is recommended for use in documentation or as examples.

>".invalid" is intended for use in online construction of domain
names that are sure to be invalid and which it is obvious at a
glance are invalid.

>The ".localhost" TLD has traditionally been statically defined in
host DNS implementations as having an A record pointing to the
loop back IP address and is reserved for such use.  Any other use
would conflict with widely deployed code which assumes this use.

https://tools.ietf.org/html/rfc2606

**Comment by cristianoliveira** [comment]
For whom is trying to find a solution for this.
As an alternative for when this error happens you can set `ergo` as your Web Proxy directly. Not through `proxy.pac` and "Automatic Proxy Configuration". Then all traffic will pass through `ergo` and it will work.

**Comment by cristianoliveira** [comment]
Partially addressed by #71
