### ISSUE TITLE
feature: Install script for Windows

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#59]
The issue #54 brought a good idea. In order to make easy installing ergo for Windows I think we can have a script  like `install.sh` that we have for linux.

**Comment by adiclepcea** [comment]
I believe that we can go one step further. An setup could be a better option for Windows. 
It could also be used to add a service. I think I will try it.

**Comment by adiclepcea** [comment]
I made a simple install script for windows. It was tested on windows 10.
The setup would be an option too, but that would mean the modification of the appveyor setup so that the appveyor build would generate the setup exe.

**Comment by cristianoliveira** [comment]
Merged!
Should we include this method of installation on README? Or do u think we can leave it as an alternative only?

**Comment by adiclepcea** [comment]
I believe we should include it. I will make another commit with it.

**Comment by adiclepcea** [comment]
Done in #69. After merging it, this can be closed.

**Comment by cristianoliveira** [comment]
Fixed!
