### ISSUE TITLE
tests: Improve unit tests codecoverage

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#61]
Thanks to @adiclepcea and his great work with the integration tests ergo is mostly covered by tests!  🥂 

Although we are mostly covered, it doesn't reflect on `codecov.io`  cause it gets only test coverage by "unit tests" and on the integration tests we use a compiled ergo's binary.

Today at codecov we have the follow report:

folder/file | lines | lines hit| lines partially | lines missing | %
-- | -- | -- | -- | -- | --
commands | 212 | 0 | 0 | 0 | 0%
-- | -- | -- | -- | -- | --
proxy | 138 | 71 | 6 | 61 | 51.44%
-- | -- | -- | -- | -- | --
main.go | 59 | 48 | 5 | 6 | 81.35%

Would be nice to improve coverage in `proxy` folder and has at least some in `commands` 😅

**Comment by cristianoliveira** [comment]
Please feel free to make any refactor needed in order to achieve it ;)

**Comment by adiclepcea** [comment]
Addressed by #63.
Improvements still possible.

**Comment by adiclepcea** [comment]
I've merged #63.
If there will be no comments on #65, I will also merge it later. I hope it is ok to do so.
On #65 some code repetition at least could be improved, but that is a good hacktober target for someone.

**Comment by adiclepcea** [comment]
Ergo is over 80%. :+1:

**Comment by cristianoliveira** [comment]
We reached 80% on overall 🎉 🍾 👏 

I think we can close this one for now :)
