### ISSUE TITLE
docs: Does ergo need a separated documentations already?

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#76]
I was thinking now that it's starting to have more options/commands/configs if `ergo` need some kind of documentation. Is it already necessary?

**Comment by hmleal** [comment]
No

**Comment by jonathansp** [comment]
No.

**Comment by cesarsl** [comment]
No.

**Comment by icaromh** [comment]
No

**Comment by marcelosoares** [comment]
hmmm... no

**Comment by pedrokiefer** [comment]
No.

**Comment by lucasts** [comment]
Yes, good idea

**Comment by cristianoliveira** [comment]
<img src="https://media.giphy.com/media/Yl5aO3gdVfsQ0/giphy.gif" />

**Comment by cristianoliveira** [comment]
Properly labeled 
<img src="https://pbs.twimg.com/media/BMhppnDCIAM7QCi.jpg:large" />

**Comment by gmotta** [comment]
No.

![Image of Rubinho](http://cidadeverde.com/assets/uploads/noticias/1ababa12.jpg)

**Comment by cristianoliveira** [comment]
I will close this issue since the HueHueBr is no longer maintained. 🤣
