### ISSUE TITLE
refactor: Do we need the channels to update the configs?

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#89]
I got another feedback from the Slack Channel:

>`WatchConfigFile` can run in parallel and change `Services` by itself behind a mutex, because that's basically what happens right not anyways.

Other:
>Anyone access this config can be synchronized using the same mutex. The caller already has the goroutines. This is not an orchestration problem but a synchronization problem.

So I am thinking that we can get rid of the channels and just work with the mutex + gorotine for this case.

**Comment by adiclepcea** [comment]
We can use either one. The solution already does this (as mentioned in the first comment)  and the second comment is right. This is a synchronization problem. 
You can use either channels or mutexes. If you remember, my first proposition was with mutexes. 
You can even use rwmutexes. 
In  previous comment you mentioned using maps.  That is ok, but maps in Go are not thread safe.
You have to synchronize access to them (in the last version I think they have introduced synchronized maps, but you are also compiling against older versions (on Travis)).
What I mean is that the solution was okay it was.  There was only one writer to the config and that was synchronized by a channel.

**Comment by cristianoliveira** [comment]
> You can use either channels or mutexes. If you remember, my first proposition was with mutexes.

I remember this. You were totally right :)

> In a previous comment you mentioned using maps. That is ok, but maps in Go are not thread safe.
Also true. We still need the mutexes

>What I mean is that the solution was okay as it was. There was only one writer to the config and that was synchronized by a channel.
Am I missing something?

If I remember I may have to mislead the implementation that's why I thought it was a case for use of the "Share Memory By Communicating" Principle.

I was talking with some guys from Gopher slack channel (gophers.slack.com) that made good points about the ergo's code :)

**Comment by adiclepcea** [comment]
:+1:
