### ISSUE TITLE
Feature: new command to add service

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#9]
Create a command that would do the same as `echo "service http://service.de" >> .ergo` just for convenience. 

The idea is a command like this:
```
ergo add <localname> <url:port>
```
Once we call this, I hope the app +url will be included into `.ergo` file

**Comment by sitaramshelke** [comment]
Looking at this one.

**Comment by cristianoliveira** [comment]
Hey @sitaramshelke thanks! I will update the description. I just noticed that it is a little bit vague. I hope you had caught. :)

**Comment by cristianoliveira** [comment]
It was fixed by c20fc7fb8ad62486b04f5d47d5e2c45e527a7eb5
