### ISSUE TITLE
bug: Verbose option is not working

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#91]
Running ergo run using verbose flag is not working. Mainly because the subcomand `run` doesn't accept the verbose flag even though the usage says. 

It's a good opportunity to sort the way we currently manage the flags its becoming complex because it has more subcommands than at the beginning. 

This is the problematic line
https://github.com/cristianoliveira/ergo/blob/master/main.go#L96

Would be nice to have tests for it.

**Comment by cristianoliveira** [comment]
Some alternatives we may can use:
- https://github.com/docopt/docopt.go
I like docopt standard it is a well known in Python and it has many implementations. Plus we can use our current USAGE for it

- https://github.com/spf13/cobra
It seems the most famous command line arg parser in go. Never tried but the golang community is more familiar with this one (my assumption)

**Comment by adiclepcea** [comment]
I have used cobra, it is indeed a good option, but your main will change significantly.

**Comment by cristianoliveira** [comment]
Fixed by #93
