### ISSUE TITLE
Docs: Update documentation about config

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/ergo#97]
Now that is possible to config ergo through Environment Variables, would be nice to mention it on the README.

**Comment by cristianoliveira** [comment]
Add explanation about configuring `http_proxy` in order to use ergo as a proxy for the terminal requests. 

```sh
export http_proxy="http://localhost:2000"
```

**Comment by cristianoliveira** [comment]
Added explanations on 950f5d0d52d9924f67657f34a4a26fdc63d8551d

**Comment by EdByrnee** [comment]
Hi, running on .dev doesn't work in chrome as you probably know,

The documentation says to configure the domain by running
`ergo -h`

this prints
`Usage of ergo:
  -h	Shows ergo's help.
  -v	Shows ergo's version.`

ergo -h gives

`Usage:
  ergo run [options]
  ergo list
  ergo list-names
  ergo url <name>
  ergo setup [options] [linux-gnome|osx|windows] [-remove]
  ergo add [options] <service-name> <host:port>

Options:
  -h      Shows this message.
  -v      Shows ergo's version.
  -config     Set the config file to the proxy.


run:
  -p          Set ports to proxy.
  -V          Set verbosity on output.

setup:
  -remove     Set remove proxy configurations.`

Not sure if I'm missing something but I can't see any explanation on how to configure the domain ergo listens on?

**Comment by cristianoliveira** [comment]
Hey @EdByrnee you probably are running an ergo's old version. :)

Here what looks like the help on the latest one:
```
▶ ergo -v
v0.2.2-9-g4bcd98a
----

▶ ergo -h

Ergo proxy.
The management apps running on different ports made easy through custom local domains.

Usage:
  ergo run [options]
  ergo list [options]
  ergo list-names [options]
  ergo url <name> [options]
  ergo setup [linux-gnome|osx|windows] [-remove] [options]
  ergo add <service-name> <host:port> [options]
  ergo remove <service-name|host:port> [options]

Options:
  -h      Shows this message.
  -v      Shows ergo's version.
  -config     Set the config file to the proxy. (ERGO_CONFIG_FILE)
  -domain     Set a custom domain for services. (ERGO_DOMAIN)
  -timeout    Set a custom timeout for responses. (ERGO_TIMEOUT_IN_SECONDS)
  -p          Set ports to proxy. (ERGO_PORT)
  -V          Set verbosity on output. (ERGO_VERBOSE)

  ** Use the names inside the parentesis to configure it via environment variables.

setup:
  -remove     Set remove proxy configurations.

```

**Comment by cristianoliveira** [comment]
I'll reopen the issue cause I think it needs a better explanation about how to use env var and configure the domains on README :)

**Comment by cristianoliveira** [comment]
You were right. The version `0.2.2` has no help for Env vars. I'll release a new version containing it :)

**Comment by cristianoliveira** [comment]
We just uploaded a new version `v.0.2.4` please updated it :)
